### ISSUE TITLE
Rubocop should ignore the package folders

### ISSUE THREAD

**Issue by N7K4** [toshimaru/jekyll-toc#110]
Current: 

```yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "*.gemspec"
    - "gemfiles/*"
    - Rakefile
    - Gemfile
```

**Should be:**

```yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "*.gemspec"
    - "gemfiles/*"
    - gems/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - Rakefile
    - Gemfile
```
