### ISSUE TITLE
Allow specifying custom class names

### ISSUE THREAD

**Issue by abeMedia** [toshimaru/jekyll-toc#15]
It would be great if one could set custom class names to replace `section-nav` & `toc-entry`, as well as a custom prefix to replace `toc-h`. This would allow integrating it into existing sites easily, re-using existing CSS classes.

I'm thinking something like the following set in the `_config.yml`:

```yaml
toc:
  list_class: list
  item_class: item
  item_prefix: level_
```

Resulting in:

```html
<ul class="list">
  <li class="item level_1"><a href="#heading1">Heading.1</a></li>
  <li class="item level_2"><a href="#heading2-1">Heading.2-1</a></li>
</ul>
```

I'm happy to submit a pull request if this is within scope.
