### ISSUE TITLE
<ul> elements are empty for nested toc entries

### ISSUE THREAD

**Issue by chalin** [toshimaru/jekyll-toc#35]
Using v0.3.0, I'm trying to generate a toc from h2 and h3 entries. When I try, I get an empty `<ul>` element in the place where the h3 entries should be found. For example:

```html
<ul class="section-nav nav" style="opacity: 1;">
  <li class="toc-entry toc-h2"><a href="#what-are-structural-directives">What are structural directives?</a></li>
  <li class="toc-entry toc-h2"><a href="#ngif-case-study">NgIf case study</a>
    <ul>

    </ul>
  </li>
...
```

Notice the empty nested `<ul>`. My CSS is like this:

```css
.toc-entry.toc-h2,
.toc-entry.toc-h3 {}
.toc-entry.toc-h1,
.toc-entry.toc-h4,
.toc-entry.toc-h5,
.toc-entry.toc-h6,
.no_toc {
 display: none;
}
```

cc @kwalrath
